name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/willcrichton/tetedoro.git
          CI=false npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
